### ISSUE TITLE
SQL-Error

### ISSUE THREAD

**Issue by m-art-in** [tomyvi/owntracks-php-client#22]
I run your code on a  my webhoster (strato). Unfortunatly I get an error while fetching the markers:

`Fatal error: Uncaught Error: Call to undefined method mysqli_stmt::get_result() in [SERVER]/lib/db/MySql.php:50
Stack trace:
#0 [SERVER]/lib/db/AbstractDb.php(97): MySql->query('SELECT * FROM l...', Array)
#1 [SERVER]/rpc.php(53): AbstractDb->getMarkers(1566856800, 1566943199, 500)
#2 {main}
  thrown in [SERVER]/lib/db/MySql.php on line 50`

I don't have much influence on the php-version / mysql-server, because it's a webhoster. Where could I dig into?
Thanks

**Comment by mbirth** [comment]
What PHP Version do you have?

Please check if you can enable the MySQLi Native Driver (`extension=php_mysqli_mysqlnd.dll`).

**Comment by m-art-in** [comment]
PHP Version 7.2.20
mysqli: 
![grafik](https://user-images.githubusercontent.com/15324884/63850428-4f0b6380-c994-11e9-97d7-d29557e99d46.png)

Should be ok, or?

**Comment by mbirth** [comment]
There should be a section about "mysqlnd".

**Comment by m-art-in** [comment]
Thank you very much for your help
I don't have this :-(
As I wrote: It's a webhoster and I don't have influence which libraries (only these [0]) are loaded. Is there a work around?

[0] https://www.strato.de/faq/hosting/mit-welchen-modulen-steht-php-bei-strato-zur-verfuegung/

**Comment by mbirth** [comment]
Contact your webhoster. This is against PHP's recommendation. See: https://forum.webedition.org/viewtopic.php?t=41424 .

Or you could use SQLite.

**Comment by m-art-in** [comment]
I switched to SQLite.
Do I have to set "Identification" in the OwnTracks Android App? I don't think so, or?
My recorder is still not recording. Digging into it......

**Comment by m-art-in** [comment]
Could you please give me a hint how I can push valid (test-)data via curl to the recorder? I presume the owntracks app is doing wired things and your recorder could not store the data into SQLite. Because 
`rpc.php?dateFrom=2019-09-04&dateTo=2019-09-04&accuracy=1000&action=getMarkers ` (todays date) results into error 500
